- name: Restart SSH daemon
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Execute rc.local
  ansible.builtin.command: /etc/rc.local
  changed_when: true
  register: rc_local
  failed_when: rc_local.rc != 0

- name: Update Grub configuration
  ansible.builtin.command: update-grub
  changed_when: true

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u -k all
  changed_when: true

- name: Reboot host and wait for it to restart
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 2
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 15
    test_command: whoami
