- name: Import tasks from pve_packages.yml
  ansible.builtin.import_tasks: pve_packages.yml
  tags: pve

- name: Import tasks from ssh.yml
  ansible.builtin.import_tasks: ssh.yml
  tags: ssh

- name: Import tasks from energy.yml
  ansible.builtin.import_tasks: energy.yml
  tags: energy

- name: Import tasks from storage.yml
  ansible.builtin.import_tasks: storage.yml
  tags: storage

- name: Import tasks from shell.yml
  ansible.builtin.import_tasks: shell.yml
  tags: shell

- name: Import tasks from virtualization.yml
  ansible.builtin.import_tasks: virtualization.yml
  tags: virtualization

- name: Import tasks from nvidia-driver.yml
  ansible.builtin.import_tasks: nvidia-driver.yml
  tags: nvidia-driver
