- name: Import tasks from pve_packages.yml
  ansible.builtin.import_tasks: pve_packages.yml
  tags: pve

- name: Import tasks from ssh.yml
  ansible.builtin.import_tasks: ssh.yml
  tags: ssh

- name: Import tasks from energy.yml
  ansible.builtin.import_tasks: energy.yml
  tags: energy
