- name: Disable Proxmox enterprise package list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: "^deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise"
    line: "# deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise"

- name: Disable Proxmox ceph package list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    regexp: "^deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise"
    line: "# deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise"

- name: Add Proxmox non-enterprise package list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-no-subscription.list
    line: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
    create: true
    mode: "0644"

- name: Update and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    autoremove: true
    cache_valid_time: 3600

- name: Install extra packages
  ansible.builtin.package:
    name: "{{ proxmox_packages }}"
    state: present
