---
- name: Setup Proxmox host
  hosts: proxmox
  gather_facts: true

  roles:
    - role: proxmox
      when: ansible_facts['os_family'] == "Debian"
      vars:
        proxmox_is_silverstone: "{{ inventory_hostname == 'silverstone' }}"
