name: ansible-lint

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Vault Password File
        run: mkdir ~/.ansible && echo "${{ secrets.VAULT_PASSWORD }}" > ~/.ansible/vault_password_file

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24.2.0
